import React, { useState } from "react";
import {
  ChevronRight,
  ChevronDown,
  Folder,
  FolderOpen,
  Search,
  Archive,
  GitBranch,
  PanelLeft,
  PanelRight,
  Terminal,
  Sun,
  Moon,
  Settings,
  Plus,
  X,
  RefreshCw,
  Columns2,
  PanelBottomClose,
  FileCode2,
  FileJson,
  FileText,
  Circle,
  ChevronsRight,
  Puzzle,
  ListChecks,
  Workflow,
  Webhook,
  Cpu,
  BookOpen,
  Check,
} from "lucide-react";

// ---- mock data -------------------------------------------------------

const workspaces = [
  {
    name: "acme-web",
    open: true,
    children: [
      {
        name: "frontend",
        open: true,
        children: [
          {
            name: "checkout",
            open: true,
            children: [
              { name: "Refactor checkout flow", status: "active", dot: "violet" },
              { name: "Payment form validation", status: "idle", dot: "sky" },
            ],
          },
          {
            name: "design-system",
            open: true,
            children: [
              { name: "Migrate to design tokens", status: "running" },
              { name: "Storybook coverage", status: "running" },
              { name: "Bump to React 19", status: "idle" },
            ],
          },
        ],
      },
      {
        name: "backend",
        open: true,
        children: [
          {
            name: "auth",
            open: true,
            children: [
              { name: "API rate limiting", status: "running" },
              { name: "OAuth device flow", status: "running" },
            ],
          },
          {
            name: "payments",
            open: true,
            children: [
              { name: "Stripe webhooks", status: "running" },
              { name: "Idempotency keys", status: "running" },
              { name: "dev server", status: "idle" },
            ],
          },
        ],
      },
      {
        name: "testing",
        open: true,
        children: [
          { name: "E2E flake hunt", status: "running" },
          { name: "Coverage gaps", status: "running" },
        ],
      },
    ],
  },
  {
    name: "ml-pipeline",
    open: true,
    children: [
      {
        name: "training",
        open: true,
        children: [
          { name: "Feature extraction", status: "running" },
          { name: "Hyperparam sweep", status: "running" },
        ],
      },
      {
        name: "serving",
        open: true,
        children: [
          { name: "Model rollout", status: "idle" },
          { name: "Latency profiling", status: "idle" },
          { name: "Data drift report", status: "error" },
        ],
      },
    ],
  },
  {
    name: "infra",
    open: true,
    children: [
      {
        name: "terraform",
        open: true,
        children: [
          { name: "Terraform audit", status: "error" },
          { name: "VPC refactor", status: "idle" },
        ],
      },
      { name: "k8s", open: true, children: [{ name: "k8s upgrade", status: "error" }] },
    ],
  },
];

const dotColor = {
  violet: "bg-violet-400",
  sky: "bg-sky-400",
};

const statusDot = (status, dot) => {
  if (dot) return dotColor[dot];
  if (status === "running") return "bg-orange-500/70";
  if (status === "error") return "bg-rose-500";
  return "bg-neutral-600";
};

const tabs = [
  { id: 1, label: "Refactor checkout…", active: true, dot: "violet" },
];

const extensions = [
  {
    name: "Tasks",
    desc: "Backlog → in progress → review → done, with promotion gates.",
    icon: ListChecks,
    enabled: true,
  },
  {
    name: "Orchestration",
    desc: "Spiders every active project, usage-aware, dispatches sessions.",
    icon: Workflow,
    enabled: true,
  },
  {
    name: "Session Host",
    desc: "SDK/PTY spawn, dormant resume, tunnel-backed remote shell.",
    icon: Cpu,
    enabled: true,
  },
  {
    name: "Hooks",
    desc: "Event-spine triggers on session state changes.",
    icon: Webhook,
    enabled: false,
  },
  {
    name: "Docs Standard",
    desc: "Autogenerated repo wiki and code maps from the event log.",
    icon: BookOpen,
    enabled: false,
  },
];

// ---- tree ---------------------------------------------------------------

function TreeGroup({ node, depth = 0 }) {
  const [open, setOpen] = useState(node.open ?? true);
  const hasChildren = Array.isArray(node.children);

  if (!hasChildren) {
    return (
      <div
        className={`group flex items-center gap-2 rounded-md px-2 py-[5px] text-[13px] leading-none cursor-pointer transition-colors ${
          node.status === "active"
            ? "bg-emerald-500/10 text-neutral-100"
            : "text-neutral-400 hover:bg-white/[0.04] hover:text-neutral-200"
        }`}
        style={{ paddingLeft: 14 + depth * 14 }}
      >
        {node.status === "active" ? (
          <span className="h-1.5 w-1 rounded-full bg-emerald-400 shadow-[0_0_6px_2px_rgba(52,211,153,0.5)]" />
        ) : (
          <span
            className={`h-1.5 w-1.5 rounded-full ${statusDot(node.status, node.dot)} ${
              node.status === "running" ? "animate-pulse" : ""
            }`}
          />
        )}
        <span className="truncate">{node.name}</span>
      </div>
    );
  }

  return (
    <div>
      <button
        onClick={() => setOpen((o) => !o)}
        className="flex w-full items-center gap-1.5 rounded-md px-2 py-[5px] text-[13px] text-neutral-300 hover:bg-white/[0.04]"
        style={{ paddingLeft: depth * 14 }}
      >
        {open ? (
          <ChevronDown size={13} className="text-neutral-500 shrink-0" />
        ) : (
          <ChevronRight size={13} className="text-neutral-500 shrink-0" />
        )}
        {depth === 0 ? (
          <span className="font-semibold text-neutral-200 truncate">{node.name}</span>
        ) : (
          <>
            {open ? (
              <FolderOpen size={13} className="text-neutral-500 shrink-0" />
            ) : (
              <Folder size={13} className="text-neutral-500 shrink-0" />
            )}
            <span className="truncate">{node.name}</span>
          </>
        )}
      </button>
      {open && (
        <div>
          {node.children.map((child, i) => (
            <TreeGroup key={i} node={child} depth={depth + 1} />
          ))}
        </div>
      )}
    </div>
  );
}

// ---- diff block -----------------------------------------------------

function DiffLine({ type, children }) {
  const styles =
    type === "add"
      ? "text-emerald-400 bg-emerald-500/[0.06]"
      : type === "del"
      ? "text-rose-400 bg-rose-500/[0.06]"
      : "text-neutral-400";
  const sign = type === "add" ? "+" : type === "del" ? "-" : " ";
  return (
    <div className={`px-4 py-[1px] whitespace-pre ${styles}`}>
      <span className="select-none opacity-60 mr-2">{sign}</span>
      {children}
    </div>
  );
}

function ExtensionToggle({ on }) {
  return (
    <div
      className={`relative h-[15px] w-[26px] shrink-0 rounded-full transition-colors ${
        on ? "bg-orange-500/80" : "bg-white/10"
      }`}
    >
      <div
        className={`absolute top-[2px] h-[11px] w-[11px] rounded-full bg-neutral-100 transition-all ${
          on ? "left-[13px]" : "left-[2px]"
        }`}
      />
    </div>
  );
}

// ---- main -------------------------------------------------------------

export default function VimesTerminal() {
  const [input, setInput] = useState("");
  const [rightTab, setRightTab] = useState("files");

  return (
    <div className="h-[860px] w-full bg-[#0b0c0e] text-neutral-200 flex flex-col font-sans antialiased select-none rounded-lg overflow-hidden border border-white/[0.06]">
      {/* title bar */}
      <div className="h-9 shrink-0 flex items-center justify-between px-3 bg-[#111214] border-b border-white/[0.06] text-[12px]">
        <div className="flex items-center gap-2">
          <div className="h-4 w-4 rounded-[4px] bg-gradient-to-br from-orange-400 to-rose-500 flex items-center justify-center">
            <Terminal size={10} className="text-black" strokeWidth={2.5} />
          </div>
          <span className="font-semibold tracking-tight text-neutral-100">Vimes</span>
          <span className="text-neutral-600">·</span>
          <span className="text-neutral-500">terminal</span>
          <ChevronRight size={11} className="text-neutral-700" />
          <span className="text-neutral-500">agents</span>
        </div>
        <div className="flex items-center gap-3">
          <span className="flex items-center gap-1.5 rounded-full bg-emerald-500/10 px-2 py-[3px] text-[11px] text-emerald-400 font-medium">
            <span className="h-1.5 w-1.5 rounded-full bg-emerald-400" />
            DEV · 16:36:21
          </span>
          <div className="flex items-center gap-2.5 text-neutral-500">
            <PanelRight size={14} className="hover:text-neutral-300 cursor-pointer" />
            <Moon size={14} className="hover:text-neutral-300 cursor-pointer" />
            <Sun size={14} className="hover:text-neutral-300 cursor-pointer" />
            <Settings size={14} className="hover:text-neutral-300 cursor-pointer" />
            <PanelLeft size={14} className="hover:text-neutral-300 cursor-pointer" />
            <PanelRight size={14} className="hover:text-neutral-300 cursor-pointer" />
          </div>
        </div>
      </div>

      <div className="flex flex-1 min-h-0">
        {/* left sidebar */}
        <div className="w-[240px] shrink-0 border-r border-white/[0.06] bg-[#0d0e10] flex flex-col">
          <div className="flex items-center justify-between px-3 pt-3 pb-2">
            <span className="text-[10px] tracking-[0.12em] font-semibold text-neutral-500">
              WORKSPACE
            </span>
            <div className="flex items-center gap-2 text-neutral-500">
              <Folder size={12} className="hover:text-neutral-300 cursor-pointer" />
              <GitBranch size={12} className="hover:text-neutral-300 cursor-pointer" />
              <Search size={12} className="hover:text-neutral-300 cursor-pointer" />
              <Puzzle size={12} className="hover:text-neutral-300 cursor-pointer" />
              <Archive size={12} className="hover:text-neutral-300 cursor-pointer" />
            </div>
          </div>
          <div className="px-2 pb-2">
            <div className="flex items-center gap-2 rounded-md bg-white/[0.03] border border-white/[0.05] px-2 py-1.5 text-[12px] text-neutral-500">
              <Search size={12} />
              Search sessions / g…
            </div>
          </div>

          {/* usage window — first class, sits directly above the sessions it funds */}
          <div className="mx-2 mb-2 rounded-md border border-white/[0.06] bg-white/[0.02] px-2.5 py-2">
            <div className="flex items-baseline justify-between mb-1.5">
              <span className="text-[10px] tracking-[0.1em] font-semibold text-neutral-500">
                5H WINDOW
              </span>
              <span className="text-[11px] font-medium text-neutral-300">3h 12m left</span>
            </div>
            <div className="h-[5px] w-full rounded-full bg-white/[0.06] overflow-hidden flex">
              <div className="h-full bg-orange-400/80" style={{ width: "38%" }} />
              <div className="h-full bg-orange-400/35" style={{ width: "17%" }} />
            </div>
            <div className="flex items-center justify-between mt-1.5 text-[10.5px]">
              <span className="text-neutral-500">
                <span className="text-orange-400">55%</span> used · 4 running
              </span>
              <span className="text-neutral-600">7d: 41%</span>
            </div>
          </div>
          <div className="flex-1 overflow-y-auto px-1.5 pb-2">
            {workspaces.map((ws, i) => (
              <TreeGroup key={i} node={ws} depth={0} />
            ))}
          </div>
        </div>

        {/* center */}
        <div className="flex-1 min-w-0 flex flex-col bg-[#0a0b0d]">
          {/* tab bar */}
          <div className="h-9 shrink-0 flex items-center border-b border-white/[0.06] bg-[#0d0e10] px-1">
            {tabs.map((t) => (
              <div
                key={t.id}
                className="flex items-center gap-2 h-full px-3 border-r border-white/[0.06] bg-[#0a0b0d] text-[12.5px] text-neutral-200 max-w-[220px]"
              >
                <span className="h-1.5 w-1.5 rounded-full bg-violet-400 shrink-0" />
                <span className="truncate">{t.label}</span>
                <X size={12} className="text-neutral-600 hover:text-neutral-300 shrink-0" />
              </div>
            ))}
            <button className="flex items-center justify-center h-full w-8 text-neutral-500 hover:text-neutral-300">
              <Plus size={14} />
            </button>
          </div>

          {/* session header */}
          <div className="h-9 shrink-0 flex items-center justify-between px-4 border-b border-white/[0.06] text-[12px]">
            <div className="flex items-center gap-2 text-neutral-400">
              <ChevronsRight size={13} className="text-neutral-600" />
              <span>Refactor checkout flow</span>
            </div>
            <div className="flex items-center gap-3 text-neutral-500">
              <span className="flex items-center gap-1">
                <Circle size={7} className="fill-emerald-400 text-emerald-400" />
                <GitBranch size={11} /> main
              </span>
              <RefreshCw size={12} className="hover:text-neutral-300 cursor-pointer" />
              <Columns2 size={13} className="hover:text-neutral-300 cursor-pointer" />
              <PanelBottomClose size={13} className="hover:text-neutral-300 cursor-pointer" />
              <X size={13} className="hover:text-neutral-300 cursor-pointer" />
            </div>
          </div>

          {/* transcript */}
          <div className="flex-1 overflow-y-auto px-6 py-5 text-[13px] leading-relaxed">
            {/* user turn */}
            <div className="rounded-md bg-white/[0.035] border border-white/[0.06] px-3 py-2 text-neutral-300 mb-5">
              <span className="text-neutral-600 mr-2">{">"}</span>
              Reply in English: outline a 5-step plan to refactor the checkout flow for
              accessibility, one short line per step, then a 6-line example diff for step 1.
            </div>

            {/* assistant turn */}
            <div className="flex gap-3">
              <div className="h-7 w-7 shrink-0 rounded-md bg-gradient-to-br from-orange-300 to-rose-400 flex items-center justify-center text-[11px] font-bold text-black/70">
                V
              </div>
              <div className="flex-1 min-w-0 space-y-4">
                <div className="text-neutral-500 text-[12px]">
                  <span className="font-semibold text-neutral-300">Claude Code</span> v2.1.202
                  <br />
                  Opus 4.8 (1M context) with xhigh effort · Claude Max
                  <br />
                  <span className="text-neutral-600">~/vmx-demo/acme-web</span>
                </div>

                <p className="text-neutral-200">
                  <span className="text-orange-400 font-medium">vmx</span> — here's the plan.
                </p>

                <ol className="space-y-1.5 text-neutral-300 list-decimal list-inside marker:text-neutral-600">
                  <li>
                    Add explicit <code className="text-sky-400">&lt;label&gt;</code> +{" "}
                    <code className="text-sky-400">id</code> associations and ARIA attributes to
                    every checkout form field.
                  </li>
                  <li>Enforce a logical tab order with visible, high-contrast focus indicators across each step.</li>
                  <li>
                    Wire validation errors to their fields via{" "}
                    <code className="text-sky-400">aria-describedby</code> and announce them with{" "}
                    <code className="text-sky-400">aria-live</code>.
                  </li>
                  <li>Make the step/progress indicator keyboard-operable and expose current step to screen readers.</li>
                  <li>Audit color contrast and add landmark regions plus a skip-to-main link.</li>
                </ol>

                <div>
                  <p className="text-neutral-300 mb-2">Example diff for step 1:</p>
                  <div className="rounded-md border border-white/[0.06] bg-[#0d0e10] py-2 font-mono text-[12.5px] overflow-x-auto">
                    <DiffLine type="del">{`<input type="email" name="email" placeholder="Email" />`}</DiffLine>
                    <DiffLine type="add">{`<label htmlFor="email">Email address</label>`}</DiffLine>
                    <DiffLine type="add">{`<input id="email" type="email" name="email"`}</DiffLine>
                    <DiffLine type="add">{`       autoComplete="email"`}</DiffLine>
                    <DiffLine type="add">{`       aria-required="true"`}</DiffLine>
                    <DiffLine type="add">{`       aria-describedby="email-error" />`}</DiffLine>
                  </div>
                </div>

                <p className="text-neutral-300">
                  Want me to apply step 1 to the actual checkout components in this repo? If so,
                  point me at the checkout directory (or I can locate it) and I'll draft the real
                  changes.
                </p>

                <p className="text-neutral-600 text-[12px] pt-1">* Churned for 20s</p>
              </div>
            </div>
          </div>

          {/* input */}
          <div className="shrink-0 border-t border-white/[0.06] px-4 py-3">
            <div className="flex items-center gap-2 rounded-md border border-white/[0.08] bg-white/[0.02] px-3 py-2">
              <span className="text-neutral-600">{">"}</span>
              <input
                value={input}
                onChange={(e) => setInput(e.target.value)}
                placeholder="Message vmx…"
                className="flex-1 bg-transparent outline-none text-[13px] text-neutral-200 placeholder:text-neutral-600"
              />
            </div>
            <div className="flex items-center justify-between pt-2 text-[11px] text-neutral-600">
              <span>bypass permissions on (shift+tab to cycle) · ← for agents</span>
            </div>
          </div>
        </div>

        {/* right files panel */}
        <div className="w-[260px] shrink-0 border-l border-white/[0.06] bg-[#0d0e10] flex flex-col">
          <div className="h-9 shrink-0 flex items-center gap-4 px-3 border-b border-white/[0.06] text-[12px]">
            {[
              { id: "files", label: "Files" },
              { id: "extensions", label: "Extensions" },
              { id: "info", label: "Info" },
              { id: "git", label: "Git" },
            ].map((t) => (
              <button
                key={t.id}
                onClick={() => setRightTab(t.id)}
                className={`h-full flex items-center transition-colors ${
                  rightTab === t.id
                    ? "text-neutral-100 font-medium border-b-2 border-orange-400"
                    : "text-neutral-500 hover:text-neutral-300"
                }`}
              >
                {t.label}
              </button>
            ))}
          </div>

          {rightTab === "files" && (
            <>
              <div className="px-3 py-2 flex items-center gap-2 text-neutral-500 text-[11px] border-b border-white/[0.06]">
                <Search size={11} />
                <span className="flex-1">acme-web</span>
              </div>
              <div className="flex-1 overflow-y-auto py-2 text-[12.5px]">
                <div className="flex items-center gap-1.5 px-3 py-[5px] text-neutral-300">
                  <ChevronDown size={12} className="text-neutral-500" />
                  <FolderOpen size={13} className="text-neutral-500" />
                  <span className="font-medium">acme-web</span>
                </div>
                {[
                  { name: "docs", type: "folder" },
                  { name: "src", type: "folder" },
                ].map((f) => (
                  <div
                    key={f.name}
                    className="flex items-center gap-1.5 pl-6 pr-3 py-[5px] text-neutral-400 hover:bg-white/[0.03]"
                  >
                    <ChevronRight size={12} className="text-neutral-600" />
                    <Folder size={13} className="text-neutral-600" />
                    {f.name}
                  </div>
                ))}
                <div className="flex items-center gap-1.5 pl-6 pr-3 py-[5px] text-neutral-300 hover:bg-white/[0.03] justify-between">
                  <div className="flex items-center gap-1.5">
                    <FileText size={13} className="text-sky-500" />
                    CLAUDE.md
                  </div>
                  <span className="text-orange-400 text-[10px] font-semibold">U</span>
                </div>
                <div className="flex items-center gap-1.5 pl-6 pr-3 py-[5px] text-neutral-400 hover:bg-white/[0.03]">
                  <FileJson size={13} className="text-amber-500" />
                  package.json
                </div>
                <div className="flex items-center gap-1.5 pl-6 pr-3 py-[5px] text-neutral-300 hover:bg-white/[0.03] justify-between">
                  <div className="flex items-center gap-1.5">
                    <FileCode2 size={13} className="text-sky-500" />
                    README.md
                  </div>
                  <span className="text-violet-400 text-[10px] font-semibold">M</span>
                </div>
              </div>
            </>
          )}

          {rightTab === "extensions" && (
            <div className="flex-1 overflow-y-auto">
              <div className="px-3 pt-3 pb-2 text-[11px] text-neutral-500">
                Engine modules — activate what this workspace needs.
              </div>
              <div className="px-1.5 space-y-1 pb-3">
                {extensions.map((ext) => {
                  const Icon = ext.icon;
                  return (
                    <div
                      key={ext.name}
                      className="flex items-start gap-2.5 rounded-md px-2.5 py-2 hover:bg-white/[0.03]"
                    >
                      <Icon size={14} className="text-neutral-500 mt-[2px] shrink-0" />
                      <div className="min-w-0 flex-1">
                        <div className="flex items-center justify-between gap-2">
                          <span className="text-[12.5px] text-neutral-200 font-medium truncate">
                            {ext.name}
                          </span>
                          <ExtensionToggle on={ext.enabled} />
                        </div>
                        <p className="text-[11px] text-neutral-500 leading-snug mt-0.5">
                          {ext.desc}
                        </p>
                      </div>
                    </div>
                  );
                })}
              </div>
              <div className="mx-3 mb-3 rounded-md border border-dashed border-white/10 px-2.5 py-2 flex items-center gap-2 text-[11px] text-neutral-600">
                <Puzzle size={12} />
                Browse the extension library
              </div>
            </div>
          )}

          {rightTab === "info" && (
            <div className="flex-1 overflow-y-auto px-3 py-3 space-y-3 text-[12px]">
              <div>
                <p className="text-neutral-500 text-[11px] mb-1">Event spine</p>
                <p className="text-neutral-300">Append-only SQLite · 14,882 events</p>
              </div>
              <div>
                <p className="text-neutral-500 text-[11px] mb-1">Access</p>
                <p className="text-neutral-300">cloudflared tunnel · single environment</p>
              </div>
              <div className="flex items-center gap-1.5 text-emerald-400">
                <Check size={13} />
                <span>Self-hosting: Vimes is building Vimes</span>
              </div>
            </div>
          )}

          {rightTab === "git" && (
            <div className="flex-1 overflow-y-auto px-3 py-3 text-[12px] text-neutral-500">
              <div className="flex items-center gap-1.5 text-neutral-300 mb-2">
                <GitBranch size={12} /> main
              </div>
              <p>No staged changes.</p>
            </div>
          )}
        </div>
      </div>

      {/* status bar */}
      <div className="h-6 shrink-0 flex items-center justify-between px-3 border-t border-white/[0.06] bg-[#111214] text-[11px] text-neutral-500">
        <span>22 sessions · Claude</span>
        <div className="flex items-center gap-3">
          <span className="flex items-center gap-1">
            <GitBranch size={10} /> main
          </span>
          <span>Perms: Ask</span>
          <span>Notify: On</span>
          <span className="flex items-center gap-1 text-emerald-500">✓ 1 Viewed</span>
          <span>Background 1/16</span>
        </div>
      </div>
    </div>
  );
}
