import { defineConfig } from 'vite';
import vue from '@vitejs/plugin-vue';
import tailwindcss from '@tailwindcss/vite';
import { VitePWA } from 'vite-plugin-pwa';

// One mobile page, built to dist/ and served by the daemon via VIMES_STATIC_DIR.
// Slice-2 step 3 adds the PWA: a manifest + an injectManifest service worker
// (src/sw.ts) that owns web-push delivery and the notification deep-link.
export default defineConfig({
  plugins: [
    vue(),
    tailwindcss(),
    VitePWA({
      // The SW auto-updates in the background; we own skipWaiting/clientsClaim in
      // src/sw.ts (injectManifest strategy — our SW, the plugin injects the
      // precache manifest at self.__WB_MANIFEST).
      registerType: 'autoUpdate',
      strategies: 'injectManifest',
      srcDir: 'src',
      filename: 'sw.ts',
      injectRegister: 'auto',
      // Exclude the CM6 and xterm lazy chunks (JS + CSS) from the SW precache: the
      // app is behind a tunnel and only opened online, so these load on demand via
      // their existing dynamic import() (src/lib/codemirror-setup.ts,
      // src/lib/xterm-setup.ts) instead of bloating SW install. Chunk names are
      // content-hashed (e.g. codemirror-setup-DJDcSLmc.js); glob on the stable prefix.
      injectManifest: {
        globIgnores: ['**/codemirror-setup-*', '**/xterm-setup-*'],
      },
      // Colors track the dark UI (bg-slate-950 background, sky-600 accent).
      manifest: {
        name: 'VIMES',
        short_name: 'VIMES',
        description: 'Agent-first remote IDE for Claude Code',
        display: 'standalone',
        start_url: '/',
        scope: '/',
        theme_color: '#0284c7',
        background_color: '#020617',
        // Icons are generated by scripts/make-icons.mjs from one set of geometry
        // constants (which also emits icon.svg — the favicon). The maskable entry
        // is a SEPARATE full-bleed image: Android crops maskable icons to the
        // device shape, so a rounded-corner source would show clipped corners.
        icons: [
          { src: 'icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
          { src: 'icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
          { src: 'icons/icon-512-maskable.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
        ],
      },
      devOptions: {
        // Keep the SW out of the way during `vite dev`; it is built for prod.
        enabled: false,
      },
    }),
  ],
  build: {
    outDir: 'dist',
    // Emit dist/.vite/manifest.json so scripts/check-build-manifest.mjs can prove
    // (deterministically, no calibration) that CM6 lives in its own lazy chunk and
    // the entry chunk never statically imports it. See docs/slice-3.md §Editor.
    manifest: true,
  },
});
